const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular white shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular white shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Reebok',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular white shirt',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Chanel',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking golf pants',
    },
    {
      name: 'Fit Pant',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 75,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Pants',
    },
    {
      name: 'Classic Pant',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'classic pants',
    },
  ],
};

export default data;
